- ec2_asg:
    name: "{{app_name}}_asg"
    load_balancers: '{{asg_loadbalancer}}'
    launch_config_name: "{{asg_launchconfig}}"
    region: "{{asg_region}}"
    min_size: "{{asg_min_size}}"
    max_size: "{{asg_max_size}}"
    desired_capacity: "{{asg_desired_capacity}}"
    vpc_zone_identifier: '{{asg_subnet}}'
    replace_all_instances: yes
    tags: "{{asg_tags|default([]) + asg_name_tag}}"
    health_check_type: "{{asg_health_check_type}}"
    wait_for_instances: "{{asg_wait_for_instances}}"
    wait_timeout: "{{asg_wait_timeout}}"
  register: asg

- debug:
    msg: "{{asg}}"