- ec2_asg:
    name: "{{app_name}}_asg"
    load_balancers: '{{asg_loadbalancer}}'
    launch_config_name: "{{asg_launchconfig}}"
    region: "{{asg_region}}"
    min_size: 1
    max_size: 2
    desired_capacity: 1
    vpc_zone_identifier: '{{asg_subnet}}'
    replace_all_instances: yes
    tags: "{{asg_tags|default([]) + asg_name_tag}}"
  register: asg

- debug:
    msg: "{{asg}}"